Added ords to the output for SORTED and SORTED_SET doc values
flaxsearch/marple pull request #21
Opened 2016-12-16 16:54 UTC by noofherder

2016-12-16 17:22 UTC, noofherder commented
TODO - add an endpoint to return ords and values without docids (and with a value filter?)

2016-12-19 15:45 UTC, romseygeek requested changes

2016-12-19 15:45 UTC, romseygeek commented on src/main/java/com/github/flaxsearch/resources/DocValuesResource.java
> +    @GET
Can we make this ```/ordered/{field}``` to keep it in line with the other endpoints?  Plus it enforces that you need a field name for it to work.

2016-12-19 15:45 UTC, romseygeek commented on src/test/java/com/github/flaxsearch/resources/TestDocValuesResource.java
> +                .get(new GenericType<AnyDocValuesResponse>() {});
You can use ```.get(AnyDocValuesResponse.class)``` here - ```GenericType``` is only needed for generics (eg Map or List).

2016-12-19 15:52 UTC, romseygeek commented on src/main/java/com/github/flaxsearch/resources/DocValuesResource.java
> +    @GET
Oh, never mind, it's a subpath.  Ignore me!

2016-12-19 15:52 UTC, noofherder commented on src/main/java/com/github/flaxsearch/resources/DocValuesResource.java
> +    @GET
Ignored with great prejudice.

2016-12-19 15:56 UTC, noofherder commented on src/test/java/com/github/flaxsearch/resources/TestDocValuesResource.java
> +                .get(new GenericType<AnyDocValuesResponse>() {});
Ta! Fixed.

2016-12-19 16:00 UTC, romseygeek approved these changes

2016-12-19 16:00 UTC, merged